community_name = "Linux Kernel"
community_description = "Maintainers of the kernel"

[server]
host = "0.0.0.0"
port = 3000

[log]
level = "info"
format = "text"

[store]
data_dir = "data/vta"

[messaging]
mediator_url = "test"
mediator_did = "test"
